// ═══════════════════════════════════════════════════════════════
// HUMA — Canvas Data Types
// Structured data that drives both the Living Canvas (spatial)
// and the Document View (print). Generated by Claude as JSON.
// ═══════════════════════════════════════════════════════════════

export type CapitalForm =
  | "financial" | "material" | "living" | "social"
  | "intellectual" | "experiential" | "spiritual" | "cultural";

export interface CapitalScore {
  form: CapitalForm;
  score: number; // 1-5
  note: string;
}

export interface FieldLayer {
  name: string;
  category: "permanent" | "development" | "management";
  status: "strong" | "adequate" | "leverage-point" | "needs-attention" | "unexplored";
  note: string;
}

export interface EnterpriseCard {
  name: string;
  category: string;
  role: "anchor" | "foundation" | "partner" | "long-game" | "multiplier";
  description: string;
  financials: {
    startup: string;
    year1: string;
    year3: string;
    laborInSeason?: string;
    laborOffSeason?: string;
    timeToRevenue?: string;
    margin?: string;
  };
  capitals: Array<{ form: CapitalForm; label: string }>;
  fitNarrative: string;
  wide?: boolean;
}

export interface CascadeStep {
  emoji: string;
  label: string;
}

export interface NodalIntervention {
  action: string;
  timing: string;
  why: string;
  cascade: CascadeStep[];
  setupFor: string;
}

export interface TimeBlock {
  time: string;
  activity: string;
  enterprise?: string;
}

export interface DayTemplate {
  day: string;
  focus: string;
  blocks: TimeBlock[];
  hardStop: string;
}

export interface WeeklyRhythm {
  days: DayTemplate[];
  peakSeason: string;
  restSeason: string;
}

export interface ValidationCheck {
  qolStatement: string;
  question: string;
  target: string;
  failureResponse: string;
}

export interface SeasonalPhase {
  name: string;
  months: string;
  primaryActivities: string[];
  qolPressure: string[];
  qolNatural: string[];
  protectAtAllCosts: string;
}

export interface QoLNode {
  statement: string;
  enablingConditions?: string[];
  weeklyCommitments?: string[];
  validationQuestion?: string;
  target?: string;
  failureResponse?: string;
}

export interface CanvasData {
  essence: { name: string; land: string; phrase: string };
  qolNodes: (string | QoLNode)[];
  productionNodes: string[];
  resourceNodes: string[];
  capitalProfile: CapitalScore[];
  fieldLayers: FieldLayer[];
  enterprises: EnterpriseCard[];
  nodalInterventions: NodalIntervention[];
  weeklyRhythm?: WeeklyRhythm;
  validationChecks?: ValidationCheck[];
  seasonalArc?: SeasonalPhase[];
  closing?: string;
  epigraph?: string;
  date?: string;
}
