interface CanvasClosingProps {
  closing?: string;
  epigraph?: string;
}

export default function CanvasClosing({ closing, epigraph }: CanvasClosingProps) {
  return (
    <div className="text-center max-w-[520px] mx-auto mt-5 mb-16 pt-10">
      {epigraph && (
        <p className="font-serif text-[1rem] font-light italic text-earth-400 leading-[1.75] mb-6">
          &ldquo;{epigraph}&rdquo;
        </p>
      )}
      {closing && (
        <p className="font-serif text-[0.9rem] font-light italic text-earth-400 leading-[1.75] mb-6">
          {closing}
        </p>
      )}
      <p className="font-serif text-[0.8rem] italic text-earth-400 leading-[1.6] mb-4">
        This map is a beginning, not a blueprint.<br />
        The land will teach you things no tool can anticipate.<br />
        Trust the conversation between you and your place.
      </p>
      <div className="font-serif text-[0.7rem] font-medium tracking-[0.3em] uppercase text-sage-500 opacity-50">
        Generated by HUMA
      </div>
    </div>
  );
}
