import type { Metadata } from "next";
import MapClient from "./MapClient";

interface MapPageProps {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ name?: string; location?: string; enterprises?: string }>;
}

export async function generateMetadata({ searchParams }: MapPageProps): Promise<Metadata> {
  const sp = await searchParams;
  const name = sp.name || "an Operator";
  const location = sp.location || "";
  const enterpriseCount = sp.enterprises || "";

  const titleParts = [`Regenerative Enterprise Map for ${name}`];
  const descParts: string[] = [];
  if (location) descParts.push(location);
  if (enterpriseCount) descParts.push(`${enterpriseCount} enterprises`);
  descParts.push("Generated by HUMA");

  const ogParams = new URLSearchParams();
  ogParams.set("name", name);
  if (location) ogParams.set("location", location);
  if (enterpriseCount) ogParams.set("enterprises", enterpriseCount);
  const ogImage = `/api/og?${ogParams.toString()}`;

  return {
    title: titleParts[0],
    description: descParts.join(" · "),
    openGraph: {
      title: titleParts[0],
      description: descParts.join(" · "),
      type: "article",
      siteName: "HUMA",
      images: [{ url: ogImage, width: 1200, height: 630, alt: `Regenerative Enterprise Map for ${name}` }],
    },
    twitter: {
      card: "summary_large_image",
      title: titleParts[0],
      description: descParts.join(" · "),
      images: [ogImage],
    },
  };
}

export default async function MapPage({ params }: MapPageProps) {
  const { id } = await params;
  return <MapClient id={id} />;
}
